name: Docker CI
on:
  push:
    branches: [ "main" ]

env:
  dockerimage_tag: ${{ github.sha }}
  dockerimage_name: ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}
          tags: |
            ${{ env.dockerimage_tag }}
            latest
          flavor: |
            latest=true
        
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Login to DockerHub
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout for Operation repository
        uses: actions/checkout@v3
        with:
          repository: SystemConsultantGroup/K8s-Resource
          ref: main  
          token: ${{ secrets.ACTION_TOKEN }}
          path: K8s-Resource

      - name: Set foobar to cool
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.spec.template.spec.containers[0].image = "${{ env.dockerimage_name }}"' 'K8s-Resource/deployment.yaml'

      - name: Commit minifest files
        run: |
          cd K8s-Resource
          git config --global user.email "sce06147@gmail.com"
          git config --global user.name "KoHyunsu"
          git commit -am "Update image tag"
          git push -u origin main
